"""add weekly defaults

Revision ID: e22a8c06793c
Revises: 719f75470754
Create Date: 2026-09-25 16:08:32.468368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e22a8c06793c'
down_revision: Union[str, None] = '719f75470754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_defaults',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=False),
    sa.Column('pickup_window_id', sa.Integer(), nullable=True),
    sa.Column('drop_window_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drop_window_id'], ['drop_windows.id'], ),
    sa.ForeignKeyConstraint(['pickup_window_id'], ['pickup_windows.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weekly_defaults_id'), 'weekly_defaults', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_defaults_id'), table_name='weekly_defaults')
    op.drop_table('weekly_defaults')
    # ### end Alembic commands ###